apiVersion: apps/v1
kind: Deployment
metadata:
  name: hvac-controller
  namespace: grp01eq6-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hvac-controller
  template:
    metadata:
      labels:
        app: hvac-controller
    spec:
      containers:
      - name: hvac-controller
        image: log680equipe6ete24/oxygencs-grp1-eq6:latest
        envFrom:
        - configMapRef:
            name: hvac-config
        - secretRef:
            name: hvac-secrets
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
