name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run integration tests
        run: pipenv run pytest test/test_integration.py

  lint_and_format:
    runs-on: ubuntu-latest
    needs: test_integration

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          pip install black pylint

      - name: Run linting
        run: pipenv run pylint src/*.py

      - name: Run formatting
        run: pipenv run black --check .

  build_docker:
    runs-on: ubuntu-latest
    needs: lint_and_format
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: log680equipe6ete24/oxygencs-grp1-eq6:latest,log680equipe6ete24/oxygencs-grp1-eq6:${{ github.sha }}

  deploy_docker:
    runs-on: ubuntu-latest
    needs: build_docker
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: log680equipe6ete24/oxygencs-grp1-eq6:latest,log680equipe6ete24/oxygencs-grp1-eq6:${{ github.sha }}

  deploy_kubernetes:
    runs-on: ubuntu-latest
    needs: deploy_docker
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/deployment-hvac.yaml
          kubectl apply -f k8s/secret.yaml
